version: '2'
services:

###############################
   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
#
################################
#   cassandra1:
#    image: cassandra
#    container_name: cassandra1
#    ports:
#     - 9142:9042
#    links:
#     - cassandra0:seed
#    environment:
#     - CASSANDRA_SEEDS=seed
#
################################
#   cassandra2:
#    image: cassandra
#    container_name: cassandra2
#    ports:
#     - 9242:9042
#    links:
#     - cassandra0:seed
#    environment:
#     - CASSANDRA_SEEDS=seed

   zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    restart: always
    depends_on:
      - cassandra0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

   kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

   redis:
    image: redis
    ports:
     - 6379:6379
    depends_on:
      - kafka
