version: '2'
services:

###############################
   scyall0:
    image: scylladb/scylla
    container_name: scyall0
#restart: always
    ports:
     - 9042:9042
     - 9160:9160
     - 7199:7199
#
################################
#   scyall1:
#    image: scylladb/scylla
#    container_name: scyall1
#    restart: always
#    depends_on:
#      - scyall0
#    ports:
#     - 9142:9042
#    links:
#     - scyall0:seed
#    environment:
#     - SEEDS=seed
##
#################################
#   scyall2:
#    image: scylladb/scylla
#    container_name: scyall2
#    restart: always
#    depends_on:
#          - scyall0
#    ports:
#     - 9242:9042
#    links:
#     - scyall0:seed
#    environment:
#     - SEEDS=seed

   zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    #  restart: always
    depends_on:
      - scyall0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

   kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
        #    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

   redis:
    image: redis
    ports:
     - 6379:6379
    depends_on:
      - kafka
